"""add file analysis tables

Revision ID: add_file_analysis_tables
Revises: f0601e22cf8d
Create Date: 2025-12-13 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'add_file_analysis_tables'
down_revision = 'f0601e22cf8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 创建文件记录表
    op.create_table('file_records',
        sa.Column('id', sa.String(length=64), nullable=False, comment='文件唯一标识符'),
        sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
        sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='存储的文件名'),
        sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
        sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型: image/document/data'),
        sa.Column('file_format', sa.String(length=10), nullable=False, comment='文件格式: .jpg/.pdf/.csv等'),
        sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
        sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小(字节)'),
        sa.Column('description', sa.Text(), nullable=True, comment='文件描述'),
        sa.Column('upload_time', sa.DateTime(), nullable=True, comment='上传时间'),
        sa.Column('analysis_status', sa.String(length=20), nullable=True, comment='分析状态: pending/processing/completed/failed'),
        sa.Column('last_analysis_time', sa.DateTime(), nullable=True, comment='最后分析时间'),
        sa.Column('analysis_progress', sa.Float(), nullable=True, comment='分析进度(0-1)'),
        sa.Column('user_id', sa.String(length=64), nullable=True, comment='上传用户ID'),
        sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
        sa.Column('tags', sa.JSON(), nullable=True, comment='文件标签列表'),
        sa.Column('content_summary', sa.Text(), nullable=True, comment='文件内容摘要'),
        sa.Column('extracted_keywords', sa.JSON(), nullable=True, comment='提取的关键词'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否已删除'),
        sa.PrimaryKeyConstraint('id'),
        comment='文件记录表'
    )
    op.create_index(op.f('ix_file_records_id'), 'file_records', ['id'], unique=False)

    # 创建文件分析结果表
    op.create_table('file_analysis_results',
        sa.Column('id', sa.String(length=64), nullable=False, comment='分析结果唯一标识符'),
        sa.Column('file_id', sa.String(length=64), nullable=False, comment='关联的文件ID'),
        sa.Column('agent_type', sa.String(length=50), nullable=False, comment='分析Agent类型'),
        sa.Column('analysis_version', sa.String(length=20), nullable=True, comment='分析算法版本'),
        sa.Column('analysis_time', sa.DateTime(), nullable=True, comment='分析时间'),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='处理耗时(毫秒)'),
        sa.Column('confidence_score', sa.Float(), nullable=True, comment='分析置信度(0-1)'),
        sa.Column('processing_status', sa.String(length=20), nullable=True, comment='处理状态: pending/processing/completed/failed'),
        sa.Column('error_messages', sa.JSON(), nullable=True, comment='错误信息列表'),
        sa.Column('extracted_data', sa.JSON(), nullable=True, comment='提取的结构化数据'),
        sa.Column('metadata', sa.JSON(), nullable=True, comment='文件元数据'),
        sa.Column('suggested_visualizations', sa.JSON(), nullable=True, comment='推荐的可视化类型'),
        sa.Column('analysis_options', sa.JSON(), nullable=True, comment='分析时使用的选项'),
        sa.Column('model_version', sa.String(length=50), nullable=True, comment='使用的AI模型版本'),
        sa.Column('data_completeness', sa.Float(), nullable=True, comment='数据完整性评分(0-1)'),
        sa.Column('accuracy_score', sa.Float(), nullable=True, comment='准确性评分(0-1)'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='文件分析结果表'
    )
    op.create_index('idx_file_analysis_file_id', 'file_analysis_results', ['file_id'], unique=False)
    op.create_index('idx_file_analysis_status', 'file_analysis_results', ['processing_status'], unique=False)
    op.create_index('idx_file_analysis_time', 'file_analysis_results', ['analysis_time'], unique=False)
    op.create_index(op.f('ix_file_analysis_results_id'), 'file_analysis_results', ['id'], unique=False)

    # 创建文件可视化生成记录表
    op.create_table('file_visualization_generations',
        sa.Column('id', sa.String(length=64), nullable=False, comment='生成记录唯一标识符'),
        sa.Column('file_id', sa.String(length=64), nullable=False, comment='关联的文件ID'),
        sa.Column('analysis_result_id', sa.String(length=64), nullable=True, comment='关联的分析结果ID'),
        sa.Column('visualization_type', sa.String(length=50), nullable=False, comment='可视化类型'),
        sa.Column('template_id', sa.String(length=64), nullable=True, comment='使用的模板ID'),
        sa.Column('generation_parameters', sa.JSON(), nullable=True, comment='生成参数'),
        sa.Column('html_content', sa.Text(), nullable=True, comment='生成的HTML内容'),
        sa.Column('chart_data', sa.JSON(), nullable=True, comment='图表数据'),
        sa.Column('interactive_config', sa.JSON(), nullable=True, comment='交互配置'),
        sa.Column('generation_status', sa.String(length=20), nullable=True, comment='生成状态: pending/processing/completed/failed'),
        sa.Column('generation_time_ms', sa.Integer(), nullable=True, comment='生成耗时(毫秒)'),
        sa.Column('user_rating', sa.Integer(), nullable=True, comment='用户评分(1-5)'),
        sa.Column('user_feedback', sa.Text(), nullable=True, comment='用户反馈'),
        sa.Column('improvement_suggestions', sa.JSON(), nullable=True, comment='改进建议'),
        sa.Column('share_token', sa.String(length=64), nullable=True, comment='分享令牌'),
        sa.Column('export_formats', sa.JSON(), nullable=True, comment='支持的导出格式'),
        sa.Column('download_count', sa.Integer(), nullable=True, comment='下载次数'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
        sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间'),
        sa.ForeignKeyConstraint(['analysis_result_id'], ['file_analysis_results.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='文件可视化生成记录表'
    )
    op.create_index('idx_file_viz_file_id', 'file_visualization_generations', ['file_id'], unique=False)
    op.create_index('idx_file_viz_type', 'file_visualization_generations', ['visualization_type'], unique=False)
    op.create_index('idx_file_viz_status', 'file_visualization_generations', ['generation_status'], unique=False)
    op.create_index('idx_file_viz_share_token', 'file_visualization_generations', ['share_token'], unique=False)
    op.create_index(op.f('ix_file_visualization_generations_id'), 'file_visualization_generations', ['id'], unique=False)

    # 创建文件处理队列表
    op.create_table('file_processing_queue',
        sa.Column('id', sa.String(length=64), nullable=False, comment='队列任务唯一标识符'),
        sa.Column('file_id', sa.String(length=64), nullable=False, comment='关联的文件ID'),
        sa.Column('task_type', sa.String(length=50), nullable=False, comment='任务类型: analysis/visualization/enhancement'),
        sa.Column('task_priority', sa.Integer(), nullable=True, comment='任务优先级(1-10)'),
        sa.Column('task_parameters', sa.JSON(), nullable=True, comment='任务参数'),
        sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='计划执行时间'),
        sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始执行时间'),
        sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
        sa.Column('execution_status', sa.String(length=20), nullable=True, comment='执行状态: pending/running/completed/failed/cancelled'),
        sa.Column('progress_percentage', sa.Float(), nullable=True, comment='执行进度百分比'),
        sa.Column('current_step', sa.String(length=100), nullable=True, comment='当前执行步骤'),
        sa.Column('result_data', sa.JSON(), nullable=True, comment='执行结果数据'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
        sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
        sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
        sa.ForeignKeyConstraint(['file_id'], ['file_records.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment='文件处理队列表'
    )
    op.create_index('idx_file_queue_file_id', 'file_processing_queue', ['file_id'], unique=False)
    op.create_index('idx_file_queue_priority', 'file_processing_queue', ['task_priority'], unique=False)
    op.create_index('idx_file_queue_scheduled', 'file_processing_queue', ['scheduled_at'], unique=False)
    op.create_index('idx_file_queue_status', 'file_processing_queue', ['execution_status'], unique=False)
    op.create_index(op.f('ix_file_processing_queue_id'), 'file_processing_queue', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_processing_queue_id'), table_name='file_processing_queue')
    op.drop_index('idx_file_queue_status', table_name='file_processing_queue')
    op.drop_index('idx_file_queue_scheduled', table_name='file_processing_queue')
    op.drop_index('idx_file_queue_priority', table_name='file_processing_queue')
    op.drop_index('idx_file_queue_file_id', table_name='file_processing_queue')
    op.drop_table('file_processing_queue')
    op.drop_index(op.f('ix_file_visualization_generations_id'), table_name='file_visualization_generations')
    op.drop_index('idx_file_viz_share_token', table_name='file_visualization_generations')
    op.drop_index('idx_file_viz_status', table_name='file_visualization_generations')
    op.drop_index('idx_file_viz_type', table_name='file_visualization_generations')
    op.drop_index('idx_file_viz_file_id', table_name='file_visualization_generations')
    op.drop_table('file_visualization_generations')
    op.drop_index(op.f('ix_file_analysis_results_id'), table_name='file_analysis_results')
    op.drop_index('idx_file_analysis_time', table_name='file_analysis_results')
    op.drop_index('idx_file_analysis_status', table_name='file_analysis_results')
    op.drop_index('idx_file_analysis_file_id', table_name='file_analysis_results')
    op.drop_table('file_analysis_results')
    op.drop_index(op.f('ix_file_records_id'), table_name='file_records')
    op.drop_table('file_records')
    # ### end Alembic commands ###