"""创建可视化缓存数据库表

Revision ID: f0601e22cf8d
Revises: 
Create Date: 2025-12-11 20:36:01.069488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0601e22cf8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_index',
    sa.Column('keyword', sa.String(length=100), nullable=False, comment='关键词'),
    sa.Column('subject', sa.String(length=50), nullable=True, comment='相关学科'),
    sa.Column('usage_frequency', sa.Integer(), nullable=True, comment='使用频率'),
    sa.Column('last_used', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('related_keywords', sa.JSON(), nullable=True, comment='相关关键词JSON数组'),
    sa.Column('vector_embedding', sa.Text(), nullable=True, comment='向量embeddings(JSON格式)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('keyword')
    )
    op.create_index('idx_keywords_frequency', 'keyword_index', ['usage_frequency'], unique=False)
    op.create_index('idx_keywords_last_used', 'keyword_index', ['last_used'], unique=False)
    op.create_index('idx_keywords_subject', 'keyword_index', ['subject'], unique=False)
    op.create_table('visualization_records',
    sa.Column('id', sa.String(length=64), nullable=False, comment='唯一标识符'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='用户输入的提示词'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='标准化后的关键词，逗号分隔'),
    sa.Column('subject', sa.String(length=50), nullable=True, comment='学科分类'),
    sa.Column('template_id', sa.String(length=64), nullable=True, comment='使用的模板ID'),
    sa.Column('generation_source', sa.String(length=20), nullable=True, comment='生成来源: mock/llm/template'),
    sa.Column('html_content', sa.Text(), nullable=True, comment='生成的HTML内容'),
    sa.Column('parameters_used', sa.JSON(), nullable=True, comment='实际使用的参数JSON'),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True, comment='生成耗时(毫秒)'),
    sa.Column('cache_hit', sa.Boolean(), nullable=True, comment='是否为缓存命中'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('quality_score', sa.Float(), nullable=True, comment='质量评分(0-5)'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='缓存过期时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_records_cache_active', 'visualization_records', ['cache_hit', 'expires_at'], unique=False)
    op.create_index('idx_records_created_at', 'visualization_records', ['created_at'], unique=False)
    op.create_index('idx_records_source', 'visualization_records', ['generation_source'], unique=False)
    op.create_index('idx_records_subject', 'visualization_records', ['subject'], unique=False)
    op.create_index('idx_records_usage_count', 'visualization_records', ['usage_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_records_usage_count', table_name='visualization_records')
    op.drop_index('idx_records_subject', table_name='visualization_records')
    op.drop_index('idx_records_source', table_name='visualization_records')
    op.drop_index('idx_records_created_at', table_name='visualization_records')
    op.drop_index('idx_records_cache_active', table_name='visualization_records')
    op.drop_table('visualization_records')
    op.drop_index('idx_keywords_subject', table_name='keyword_index')
    op.drop_index('idx_keywords_last_used', table_name='keyword_index')
    op.drop_index('idx_keywords_frequency', table_name='keyword_index')
    op.drop_table('keyword_index')
    # ### end Alembic commands ###
